package day0202;

public class UseRuntimeException {

	public static void main(String[] args) {

		
		
		
		
		
		int num ;
		int num2 ;
		int result ;
		
		
		try {
			
		} catch (Exception e) {
			num = Integer.parseInt(args[0]);
			num2 = Integer.parseInt(args[1]);
			
			
			
		}
		

		
		//main method의 arguments를 두개 입력받아 나눈 연산을 수행한 후
		//결과를 보여주는 일.
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
	}//main

}//class
